# ===== APPLICATION =====
spring.application.name=messaging-service
server.port=8087

# ===== MONGODB =====
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=messaging_db

# ===== KAFKA =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer