spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.instance.prefer-ip-address=true

spring.cloud.loadbalancer.enabled=false

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when_authorized
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.90,0.95,0.99
management.metrics.distribution.slo.http.server.requests=100ms,250ms,500ms,1s
