package com.mediconnect.dmp.dto.request;

import com.mediconnect.dmp.model.Allergy;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
 * This is what the client (Postman / frontend) sends in the REQUEST BODY.
 * We use @NotBlank / @NotNull to validate the input BEFORE it reaches the service.
 *
 * WHY separate from the Model?
 * - We don't want the client to set 'id', 'createdAt', 'patientId' manually.
 * - patientId comes from the URL path, not the body.
 * - id is generated by MongoDB automatically.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AllergyRequest {

    @NotBlank(message = "Allergen name is required")
    private String allergen;

    @NotNull(message = "Severity level is required")
    private Allergy.SeverityLevel severity;

    @NotBlank(message = "Reaction description is required")
    private String reaction;

    private String notes; // optional
}