spring.application.name=teleconsultation-service
server.port=8086
spring.data.mongodb.uri=mongodb://localhost:27017/mediconnect_teleconsultation
spring.kafka.bootstrap-servers=localhost:9092
recording.retention.years=2
