spring.application.name=teleconsultation-service
server.port=8086
spring.data.mongodb.uri=mongodb://localhost:27017/mediconnect_teleconsultation
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
recording.retention.years=2
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
