spring.application.name=appointment-service
server.port=8085

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mediconnect_appointments}
spring.mongodb.uri=${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mediconnect_appointments}}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
medconnect.teleconsultation.base-url=${MEDCONNECT_TELECONSULTATION_BASE_URL:http://localhost:8086/api/teleconsult}

# ===== EUREKA =====
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
