spring.application.name=appointment-service
server.port=8085

spring.data.mongodb.uri=mongodb://medconnect-mongodb:27017/mediconnect_appointments
spring.kafka.bootstrap-servers=medconnect-kafka:9092
spring.data.redis.host=medconnect-redis
spring.data.redis.port=6379

# ===== EUREKA =====
eureka.client.service-url.defaultZone=http://medconnect-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true